config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'application#index'

  get 'redirect/:monitor_id', controller: :redirects, action: :redirect, as: :redirect

  namespace :about do
    root '', action: :index
  end

  namespace :resources do
    root '', action: :index
  end

  devise_for :users

  resources :users, only: [] do
    resources :rss_feeds, only: :show
  end

  namespace :current_user do
    resource :profile
    resource :notifications, only: :show
    resources :rss_feeds

    resources :selector_suggestions, only: [:new, :create]
    get 'selector_suggestions/success'
  end

  namespace :u do
    get ':slug', controller: :public_dashboards, action: :show
  end

  namespace :admin do
    resources :users
    resources :app_monitors
    resources :monitor_results do
      get :diff
    end
    resources :selector_suggestions do
      post :confirm
    end
    resources :notifications
    resources :user_categories
    resources :user_monitors

    root to: "users#index"
  end

  namespace :api do
    scope :v1 do
      resources :refresh_app_monitor, only: :create
      resources :clear_notifications, only: :create
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :user_categories do
    resources :user_monitors, shallow: true
  end
end

app/views/dashboard/_create_new_monitor.html.erb
<div class="new-link-monitor-container">
  <%= form_for [category, UserMonitor.new], html: { class: 'form-group' } do  |f| %>
    <div class="form-group">
      <%= f.text_field :name, required: true, placeholder: "Name", class: 'form-control form-control-sm' %>
    </div>
    <div class="form-group">
      <%= f.text_field :url, required: true, pattern: ".+\\..+", placeholder: "URL", class: 'form-control form-control-sm' %>
    </div>
    <%= f.submit "Create Link", class: 'btn btn-sm btn-info form-control form-control-sm new-monitor-submit-button' %>
  <% end %>
</div>

app/views/dashboard/_update_monitor.html.erb
<div class="link-form">
  <%= form_for monitor, html: { class: 'form-group' } do  |f| %>
    <div class="form-group">
      <%= f.text_field :name, class: 'form-control form-control-sm' %>
    </div>
    <div class="form-group">
      <%= f.text_field :url, class: 'form-control form-control-sm' %>
    </div>
    <div>
      <%= f.submit "Update", class: 'btn btn-sm btn-info form-control-sm' %>
      <%= link_to "Delete", user_monitor_path(monitor), method: :delete, class: 'btn btn-sm btn-danger form-control-sm' %>
    </div>
  <% end %>
</div>