config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'application#index'

  get 'redirect/:monitor_id', controller: :redirects, action: :redirect, as: :redirect

  namespace :about do
    root '', action: :index
  end

  namespace :resources do
    root '', action: :index
  end

  devise_for :users

  resources :users, only: [] do
    resources :rss_feeds, only: :show
  end

  namespace :current_user do
    resource :profile
    resource :notifications, only: :show
    resources :rss_feeds

    resources :selector_suggestions, only: [:new, :create]
    get 'selector_suggestions/success'
  end

  namespace :u do
    get ':slug', controller: :public_dashboards, action: :show
  end

  namespace :admin do
    resources :users
    resources :app_monitors
    resources :monitor_results do
      get :diff
    end
    resources :selector_suggestions do
      post :confirm
    end
    resources :notifications
    resources :user_categories
    resources :user_monitors

    root to: "users#index"
  end

  namespace :api do
    scope :v1 do
      resources :refresh_app_monitor, only: :create
      resources :clear_notifications, only: :create
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :user_categories do
    resources :user_monitors, shallow: true
  end
end

app/views/shared/_alerts.html.erb
  <div class="alert alert-success" style="<%= 'display: block;' if notice %>" role="alert">
    <%= notice %>
  </div>


  <div class="alert alert-danger" style="<%= 'display: block;' if alert %>" role="alert">
    <div>
      <%= alert %>
    </div>
    <small><%= flash[:error] %></small>
  </div>

app/views/shared/_footer.html.erb
<footer class="sticky-footer">
  <div class="container">
    <div class="text-center">
      <small>Copyright © DIY RSS 2018</small>
    </div>
  </div>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">

  <%= image_tag("rss.svg", class: "navbar-logo", width: "32px", alt: "logo") %>

  <%= link_to root_path, class: "navbar-brand" do %>
    <% if content_for? :header %>
      <% yield :header %>
    <% else %>
      DIY RSS
    <% end %>
  <% end %>

  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarResponsive">
    <%= render 'shared/sidenav' %>
    <ul class="navbar-nav ml-auto">
      <%= render 'shared/refresh_dashboard' %>
      <!--
      <%= render 'shared/notifications' %>
       -->
      <%= render 'shared/user_tools' %>
    </ul>
  </div>
</nav>

app/views/shared/_notifications.html.erb
<% if params[:controller] == "application" && params[:action] == "index" %>
  <li class="nav-item dropdown">
    <% if @notifications.present? %>
      <a class="nav-link dropdown" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-fw fa-envelope-open" data-toggle="tooltip" data-placement="bottom" title="Notifications"></i>  <span class="label">Notifications</span>
          <% if @notifications.present? %>
            <span class="d-lg-none">Alerts
              <span class="badge badge-pill badge-warning"><%= @notifications.size %> New</span>
            </span>
            <span class="indicator text-warning d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span>
          <% end %>
        </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">

        <% @notifications.each do |notif| %>
          <a class="dropdown-item" href="<%= notification_redirect_path(notif) %>" target="_blank">
            <span class="text-info">
              <strong>
                <i class="fa fa-newspaper-o"></i> Fresh Content!</strong>
            </span>
            <span class="small float-right text-muted"><%= distance_of_time_in_words(notif.created_at, Time.now.utc) %></span>
          </a>
          <div class="dropdown-divider"></div>
        <% end %>

        <div>
          <a class="dropdown-item small text-muted" href="<%= current_user_notifications_path %>">View all alerts</a>
          <a class="dropdown-item small text-muted clear-notifications-button" href="#" data-user-id="<%= current_user.id %>">Mark all as read</a>
        </div>
      </div>
    <% else %>
      <a class="nav-link" href="<%= current_user_notifications_path %>">
          <i class="fa fa-fw fa-envelope" data-toggle="tooltip" data-placement="bottom" title="Notifications"></i>
      </a>
    <% end %>
  </li>
<% end %>

app/views/shared/_refresh_dashboard.html.erb
<% if @user_categories.present? %>
  <li class="nav-item"  data-toggle="tooltip" data-placement="bottom" title="Refresh layout">
    <%= link_to '#resetLayout',  class: "nav-link refresh-layout-button" do %>
      <i class="fa fa-fw fa-refresh"></i> <span class="label">Refresh Layout</span>
    <% end %>
  </li>
<% end %>

app/views/shared/_sidenav.html.erb
<ul class="navbar-nav navbar-sidenav">
  <% if current_user.present? %>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
      <%= link_to root_path, class: "nav-link" do %>
        <i class="fa fa-fw fa-dashboard"></i> <span class="label">Dashboard</span>
      <% end %>
    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="RSS">
      <%= link_to current_user_rss_feeds_path, class: "nav-link" do %>
        <i class="fa fa-fw fa-rss"></i> <span class="label">RSS</span>
      <% end %>
    </li>
  <% end %>

  <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Resources">
    <%= link_to resources_root_path, class: "nav-link" do %>
      <i class="fa fa-fw fa-cogs"></i> <span class="label">Resources</span>
    <% end %>
  </li>
  <li class="nav-item" data-toggle="tooltip" data-placement="right" title="About">
    <%= link_to about_root_path, class: "nav-link" do %>
      <i class="fa fa-fw fa-question-circle"></i> <span class="label">About</span>
    <% end %>
  </li>
</ul>

app/views/shared/_user_tools.html.erb
<% if user_signed_in? %>
  <li class="nav-item" data-toggle="tooltip" data-placement="bottom" title="Profile">
  <%= link_to current_user_profile_path, class: "nav-link" do %>
    <i class="fa fa-fw fa-user"></i> <span class="label">Profile</span>
  <% end %>
  </li>
  <li class="nav-item">
  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
    <i class="fa fa-fw fa-sign-out"></i>Logout
  <% end %>
  </li>
<% else %>
  <li class="nav-item">
  <%= link_to new_user_session_path,  class: "nav-link" do %>
    <i class="fa fa-fw fa-sign-in"></i>Login
  <% end %>
  </li>
<% end %>