config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'application#index'

  get 'redirect/:monitor_id', controller: :redirects, action: :redirect, as: :redirect

  namespace :about do
    root '', action: :index
  end

  namespace :resources do
    root '', action: :index
  end

  devise_for :users

  resources :users, only: [] do
    resources :rss_feeds, only: :show
  end

  namespace :current_user do
    resource :profile
    resource :notifications, only: :show
    resources :rss_feeds

    resources :selector_suggestions, only: [:new, :create]
    get 'selector_suggestions/success'
  end

  namespace :u do
    get ':slug', controller: :public_dashboards, action: :show
  end

  namespace :admin do
    resources :users
    resources :app_monitors
    resources :monitor_results do
      get :diff
    end
    resources :selector_suggestions do
      post :confirm
    end
    resources :notifications
    resources :user_categories
    resources :user_monitors

    root to: "users#index"
  end

  namespace :api do
    scope :v1 do
      resources :refresh_app_monitor, only: :create
      resources :clear_notifications, only: :create
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :user_categories do
    resources :user_monitors, shallow: true
  end
end

app/models/monitor_result.rb
class MonitorResult < ApplicationRecord
  belongs_to :app_monitor, inverse_of: :monitor_results

  enum status: [
    :ok,
    :error,
  ]

  # def nextResult
  #   app_monitor.monitor_results.where('id > ?', id).first
  # end

  def previous_result
    app_monitor.monitor_results.where('id < ?', id).last
  end

  def difference_from_last_in_html
    return nil if previous_result.nil?
    diffy = Diffy::Diff.new(previous_result.payload, payload)

    return nil if diffy.diff.blank?

    Diffy::Diff.new(previous_result.payload, payload).to_s(:html)
  end
end

app/controllers/admin/monitor_results_controller.rb
module Admin
  class MonitorResultsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    def scoped_resource
      resource_class.order(created_at: :desc)
    end

    def diff
      @resource = scoped_resource.find(params.require(:monitor_result_id))
      @diff = @resource.difference_from_last_in_html
    end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   MonitorResult.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/views/admin/monitor_results/diff.html.erb
<% content_for :title, "Diff" %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>
  <div>
    <a class="button" href="<%= admin_user_monitor_path(@resource.app_monitor) %>">App Monitor</a>
  </div>
</header>

<section class="main-content__body">
  <% if @diff.present? %>
    <%= raw @diff %>
  <% else %>
    <%= render 'empty_states/monitor_result_diff' %>
  <% end %>
</section>

app/views/admin/monitor_results/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { t("administrate.actions.show_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.edit_resource", name: page.page_title),
      [:edit, namespace, page.resource],
      class: "button",
    ) if valid_action?(:edit) && show_action?(:edit, page.resource) %>
  </div>
</header>

<section class="main-content__body">
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t(
        "helpers.label.#{resource_name}.#{attribute.name}",
        default: attribute.name.titleize,
      ) %>
      </dt>

      <dd class="attribute-data attribute-data--<%=attribute.html_class%>">
        <% if attribute.name == "payload" %>
          <div class="raw-container" style="border: 1px solid grey; padding: 4px;">
            <%= raw attribute.data %>
          </div>
        <% else %>
          <%= render_field attribute %>
        <% end %>
      </dd>
    <% end %>
  </dl>
</section>